/*
Kengine ThreatMapper

Kengine Runtime API provides programmatic control over Kengine microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.2.0
Contact: community@kengine.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance{}

// ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance struct for ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance
type ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance struct {
	New []ModelCompliance `json:"new"`
}

type _ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance

// NewModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance instantiates a new ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance(new []ModelCompliance) *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance {
	this := ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance{}
	this.New = new
	return &this
}

// NewModelScanCompareResGithubComKengineThreatMapperKengineServerModelComplianceWithDefaults instantiates a new ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelScanCompareResGithubComKengineThreatMapperKengineServerModelComplianceWithDefaults() *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance {
	this := ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance{}
	return &this
}

// GetNew returns the New field value
// If the value is explicit nil, the zero value for []ModelCompliance will be returned
func (o *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) GetNew() []ModelCompliance {
	if o == nil {
		var ret []ModelCompliance
		return ret
	}

	return o.New
}

// GetNewOk returns a tuple with the New field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) GetNewOk() ([]ModelCompliance, bool) {
	if o == nil || IsNil(o.New) {
		return nil, false
	}
	return o.New, true
}

// SetNew sets field value
func (o *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) SetNew(v []ModelCompliance) {
	o.New = v
}

func (o ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.New != nil {
		toSerialize["new"] = o.New
	}
	return toSerialize, nil
}

func (o *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"new",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance := _ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance)

	if err != nil {
		return err
	}

	*o = ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance(varModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance)

	return err
}

type NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance struct {
	value *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance
	isSet bool
}

func (v NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) Get() *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance {
	return v.value
}

func (v *NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) Set(val *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) {
	v.value = val
	v.isSet = true
}

func (v NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) IsSet() bool {
	return v.isSet
}

func (v *NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance(val *ModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) *NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance {
	return &NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance{value: val, isSet: true}
}

func (v NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelScanCompareResGithubComKengineThreatMapperKengineServerModelCompliance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


